Pa 8
novotnej/petmatch_android pull request #12
Opened 2019-03-09 13:02 UTC by avb49

Added logic to User Capabilities - changes to the preferences screen are now saved for a given user to the database and upon creation of the fragment (preferences) the database is consulted for the values of the user's properties. Works for both users that do have preferences already in the database and also users that do not (in this case, an entry in the database is created for them in the user_properties table and default values set).

2019-03-09 18:16 UTC, novotnej commented on app/src/main/java/uk/ac/bath/petmatch/UserCapabilitiesActivity.java
> +        getFragmentManager().beginTransaction().add(R.id.fragment_container, userCapabilitiesFragment).commit();
getFragmentManager() is deprecated, is there another way of doing this?

2019-03-09 18:17 UTC, novotnej commented on app/src/main/java/uk/ac/bath/petmatch/Utils/UserCapabilitiesFragment.java
>  package uk.ac.bath.petmatch.Utils;
Please remove fragment from Utils package, either to the main package or create Fragments package

2019-03-09 18:18 UTC, novotnej commented on app/src/main/java/uk/ac/bath/petmatch/MainActivity.java
> +                displayNoLoginErrorAlert();
I really like the message, but also put it inside the UserCapabilitiesActivity, if a user is accidentally directed there and is not logged in

2019-03-09 18:20 UTC, novotnej commented on app/src/main/res/menu/activity_main_drawer.xml
> +            android:id="@+id/nav_user_capabilities"
in the mainactivity, perhaps in the setUpLoginView or whatever I called it, or after login, only show this when user is logged in (hidden by default). Then hide it again when user logs out. 

Similar logic to the login/logout buttons

2019-03-09 18:20 UTC, novotnej requested changes
Really impressed you got the fragment and activity working together. 

Some details that need fixing but otherwise good work

2019-03-09 18:30 UTC, avb49 commented
> Really impressed you got the fragment and activity working together.
> 
> Some details that need fixing but otherwise good work

Cheers boss

2019-03-10 11:13 UTC, novotnej approved these changes

2019-03-10 11:14 UTC, novotnej commented
You still don't have the if user is logged in check in the activity, but nvm that for now, we need to move on.. :D

2019-03-10 11:14 UTC, merged