Pa 4
novotnej/petmatch_android pull request #13
Opened 2019-03-10 13:35 UTC by avb49

Incorporated logic in ShelterPublicProfileActivity to load attributes from a given shelter into the profile. Textviews and editTextviews are set to non-editable.
Changes in layout in the relevant xml file.

2019-03-11 13:11 UTC, novotnej commented on app/src/main/java/uk/ac/bath/petmatch/Database/ShelterDao.java
> +        List<User> results = this.queryForEq("id", shelterId);
This is a list with <Shelter> items

2019-03-11 13:20 UTC, novotnej requested changes
The address end e-mail fields still look as editable fields
Remove the android picture and move up the information
Use the real charity number instead of a dummy
Add Phone to the model and database
Make e-mail clickable, to open an e-mail client and sent e-mail to that address (MailTo)

Move the details up a bit and put a map under it with a pin in the gps coordinates

2019-03-13 14:05 UTC, avb49 commented
Changes have been done. 
Remember to log in as shelter@petmatch.com to see the shelter profile details being retrieved and displayed. Otherwise, some default field strings are displayed on the screen and the map has no pin.

2019-03-13 16:25 UTC, novotnej requested changes
This looks really good, could you please just use the logged in version? 

Also please merge master into it, there's some conflicts

Also just in case you wanted to and definitely a nice-to-have, but would it be possible to have a "navigate to" button in the shelter? I think it might be a feature of the maps view, or of the marker, but not sure

2019-03-13 20:10 UTC, avb49 commented
When you say merge master, what exactly do you mean?
Should I just do 'git merge master' on the PA-4 branch?

2019-03-13 20:35 UTC, novotnej commented
yep exactly that, if you want to merge anything into master (or any other branch for that matter) first you merge master into it (into PA-4) and resolve the conflicts, then you have to make sure everything is still working and then it can be all merged into master

2019-03-13 22:06 UTC, avb49 commented
alright cool. Will do

2019-03-13 22:22 UTC, avb49 commented
Should be good now.

2019-03-14 00:38 UTC, novotnej commented
Did couple of changes, namely replaced the edit views with textviews, merging it now

2019-03-14 00:38 UTC, novotnej approved these changes

2019-03-14 00:39 UTC, merged