PA-12 grid
novotnej/petmatch_android pull request #15
Opened 2019-03-11 18:47 UTC by hester-g

2019-03-11 19:17 UTC, novotnej commented on app/src/main/res/values/strings.xml
> +
This looks like a leftover of some conflict resolution, these **new** strings apart from the two you added are no longer in use

2019-03-11 22:31 UTC, novotnej requested changes
- Set the images for pets in DBHelper, currently all pets show up with the default snape
- Remove unused strings in strings.xml
- Missing onclick action when a pet image is clicked

2019-03-11 22:36 UTC, hester-g commented
@novotnej 

- when you say set images, do you mean the images for the dogs? also the default should be dumbledore.
- will do
- what should happen when a pet is clicked?

2019-03-11 22:43 UTC, novotnej commented
Onclick used to be in the createDummyPetsListView method. Joshua changed it a little bit, so please use the version in PA-7

I don't see the image value being set anywhere, so I presume you may have changed it directly in the database? This is what I see right now

![screen](https://i.snag.gy/DtxYn0.jpg)

2019-03-11 22:53 UTC, hester-g commented
Oh yeah I changed it in the database, is that not what I should do?

2019-03-11 22:56 UTC, novotnej commented
It would be nice for us and for the demo if we could all see different
images :D

On Mon, 11 Mar 2019 at 22:53, Hester G <notifications@github.com> wrote:

> Oh yeah I changed it in the database, is that not what I should do?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/novotnej/petmatch_android/pull/15#issuecomment-471772332>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/ADh86Fw7DNLs2Wy-dt3sv-spKT-K3yt8ks5vVt6AgaJpZM4bpUH6>
> .
>

2019-03-11 23:01 UTC, hester-g commented
oh i thought what I had done did that 😬

2019-03-11 23:02 UTC, novotnej commented
Nope, the database is generated with each install of the app from the code in dbhelper

2019-03-11 23:03 UTC, hester-g commented
wait what i changed was in dbhelper...

2019-03-11 23:11 UTC, hester-g commented
Okay @novotnej I think I've done everything

2019-03-11 23:12 UTC, hester-g commented
(sorry I accidentally forgot to write actual commit messages for those last three commits so they still all say merge conflict resolution or smth)

2019-03-11 23:39 UTC, novotnej commented
The app's not building now, it's the strings
while I think some of those preferences strings are supposed to be there, they definitely shouldn't be coming from your commit since Artem put them there, so it will be some merge gone a bit sideways

in any case you removed two that you actually need for your activity to work.. :D in AS you can use Refactor->remove unused resources (from within the strings.xml file). Please verify the app still works afterwards

2019-03-12 09:08 UTC, hester-g commented
Okay @novotnej now I think everythings good! Sorry for the delay i fell asleep waiting for the build to finish 😂

2019-03-12 10:48 UTC, novotnej commented
Dude c'mon :D You deleted the dummy images with it and left DummyPetAdapter in there and it wouldn't build with it.. 

I fixed it now, dw

2019-03-12 10:49 UTC, novotnej approved these changes

2019-03-12 10:49 UTC, merged