PA 8 - User capabilities edit/add form
novotnej/petmatch_android pull request #4
Opened 2019-02-27 10:37 UTC by avb49

2019-02-27 11:49 UTC, novotnej commented on app/src/main/java/uk/ac/bath/petmatch/AppCompatPreferenceActivity.java
> +public abstract class AppCompatPreferenceActivity extends PreferenceActivity {
Always extend BaseActivity, otherwise DB, LoginService won't be available and menu should then also be generated in one place..

2019-02-27 11:57 UTC, novotnej requested changes
Please remove all unnecessary functionality (ie Notifications, Data & Sync) - I assume those were auto generated by android studio.. Only keep what we actually need 

All activities must extend BaseActivity

2019-02-28 21:43 UTC, avb49 commented
Changes done

2019-02-28 21:54 UTC, avb49 commented
Changes now done.

2019-03-01 09:51 UTC, novotnej approved these changes
looks good

2019-03-01 09:57 UTC, merged